bbs/urls.py
from django.urls import path
from . import views

app_name = 'bbs'    # namespace를 bbs로 지정
# http://localhost:8000/bbs/

urlpatterns = [
    path('list/', views.b_list, name='b_list'),
    path('create/', views.b_create, name='b_create'),
    path('<int:post_id>/detail/', views.b_detail, name='b_detail'),
    path('<int:post_id>/fix/', views.b_fix, name='b_fix'),
    path('<int:post_id>/b_delete/', views.b_delete, name='b_delete'),
    path('<int:post_id>/c_delete/', views.c_delete, name='c_delete'),
]

lecture/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView      # template 경로안에서만 html을 찾기위한 패키지와 클래스

# http://localhost:8000/

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),    # 기본화면 : http://localhost:8000/
    path('admin/', admin.site.urls),
    path('bbs/', include('bbs.urls'))
]

bbs/models.py
from django.db import models

# Create your models here.


class Board(models.Model):

    b_title = models.CharField('글 제목', max_length=30)
    b_author = models.CharField('작성자', max_length=20)
    b_content = models.CharField('내용', max_length=1000)
    b_date = models.DateTimeField(auto_now=True)    # 자동으로 현재 시간으로 설정해줌. (등록, 수정 어떤 경우에도)
    b_comment_count = models.IntegerField(default=0)
    b_like_count = models.IntegerField(default=0)

    def __str__(self):
        return self.b_title

# 댓글은 ajax로 구현
# class Comment(models.Model):
#
#     c_author = models.CharField(max_length=20)
#     c_content = models.CharField(max_length=100)
#     board = models.ForeignKey(Board, on_delete=models.CASCADE)
#
#     def __str__(self):
#         return self.c_content

bbs/forms.py
# 모델폼 사용하기 : 사용자 입력 변수값 처리를 용이하게 해준다. 권장되는 방법. 파일명도 forms로 정해져있다.
from django import forms
from .models import Board


class BoardForm(forms.ModelForm):   # Form을 구성하는 방법은 정해져 있으므로 외우는 수 밖에(object, Meta, model, fields)?
    class Meta:
        model = Board   # BoardForm을 통해 사용할 모델
        fields = ['b_title', 'b_author', 'b_content']     # 그 모델 안의 변수 중에서 사용자 입력으로 보여줄 것.
        widgets = {
            'b_title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '글제목'
                }
            ),
            'b_author': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '작성자'
                }
            ),
            'b_content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': '내용'
                }
            )
        }

bbs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Board
from .forms import BoardForm
# Create your views here.


def b_list(request):

    posts = Board.objects.all().order_by('-id')
    return render(request, 'bbs/list.html', {
        'posts': posts
    })
    # 여기서 render하면 templates 폴더 중에서 html파일을 찾게 되는데 bbs폴더를 만든 이유가 여기서 보인다. (찾기 위한 경로)


def b_create(request):

    if request.method == 'POST':
        # POST 방식은 새글 작성화면에서 새글 저장 버튼을 눌렀을 때 실행된 경우 = POST
        board_form = BoardForm(request.POST)    # 입력 양식 각각에 한 번에 입력해주는 방법이다.

        if board_form.is_valid():   # 정상이면
            # board_form.save()   # 입력된 값 데이터 베이스 저장하는 방법을 아래와 같이 진행한다.
            new_post = board_form.save(commit=False)
            # new_post.b_like_count=100 # 이와 같이 form에는 없는 다른 속성에 대한 값도 지정해서 저장이 가능하기 때문.
            new_post.save()
            return redirect('bbs:b_list')

    else:
        # 리스트 화면에서 새글 작성 버튼을 눌렀을 때 실행된 경우 = GET
        board_form = BoardForm()    # 사용자 입력을 받을 수 있는 양식을 Form을 통해 만든다.
        return render(request, 'bbs/create.html', {
            'board_form': board_form
        })


def b_detail(request, post_id):

    board_objects = get_object_or_404(Board, pk=post_id)
    # comment_objects = Comment.objects.select_related('Board__id')
    return render(request, 'bbs/detail.html', {
        'board_objects': board_objects
    })


def b_fix(request, post_id):

    board_objects = get_object_or_404(Board, pk=post_id)
    if request.method == 'POST':
        board_form = BoardForm(request.POST, instance=board_objects)
        # board_form.b_author = board_objects.b_author  # 글 수정에서 작성자 정보는 변동되지 않게 만들어서, 폼에 입력되야 할 작성자 변수가 누락된건가..?
        if board_form.is_valid():  # 정상이면
            board_objects = board_form.save(commit=False)
            board_objects.save()
            return redirect('bbs:b_detail', post_id=board_objects.id)
    else:
        board_form = BoardForm(instance=board_objects)
        return render(request, 'bbs/fix.html', {'board_form': board_form, 'board_objects':board_objects})


def b_delete(request, post_id):

    board_objects = get_object_or_404(Board, pk=post_id)
    board_objects.delete()
    return redirect('bbs:b_list')


def c_delete(request, comment_id):

    comment_objects = get_object_or_404(Board, pk=comment_id)
    comment_objects.delete()
    return redirect('bbs:b_detail')

bbs/templates/bbs/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block html_body %}

<div class="container">

    <h1>새글 작성</h1>

    <form {% comment %}action = "" : 현재 페이지로 request를 진행{% endcomment %}
          method="post">
        {% csrf_token %}

        {% comment %}{{ board_form }}{% endcomment %}
        {% comment %}그냥 form 객체를 가져와서 쓰면 CSS가 적용되지 않는 형태로 나온다.{% endcomment %}
        {% comment %}pip install django-bootstrap4 진행 후, settings.py에서 INSTALLED_APPS에 'bootstrap4' 등록{% endcomment %}
        {% bootstrap_form board_form %} {% comment %}위에서 load bootstrap4 해줘야 함{% endcomment %}
        <div style="float:right">
            <button type="submit"
                    class="btn btn-primary">새글 등록</button>
            <button type="button"
                    class="btn btn-warning"
                    onclick = history.back()>취소</button>
        </div>
    </form>
</div>
{% endblock %}

bbs/templates/bbs/detail.html
{% extends 'base.html' %}

{% block html_header %}

<script src="/static/js/b_del_btn.js"></script>
<script src="/static/js/comment_btn.js"></script>
<script src="/static/js/fix_btn.js"></script>
<script src="/static/js/like_btn.js"></script>
<script src="/static/js/list_btn.js"></script>

<script src="/static/css/style.css"></script>

{% endblock %}

{% block html_body %}

<div class="container">

    <h1>글 내용보기</h1>
    <p></p>
    <div>
        글 번호 : {{ board_objects.id }}
    </div>
    <p></p>
    <div>
        글 제목 : {{ board_objects.b_title }}
    </div>
    <p></p>
    <div class="row">
        <div class="col-6">작성자 : {{ board_objects.b_author }}</div>
        <div class="col-6">작성일 : {{ board_objects.b_date }}</div>
    </div>
    <p></p>
    <div class="row">
        <div class="col-6">글 내용</div>
        <div class="col-6">좋아요 : {{ board_objects.b_like_count }}</div>
    </div>
    <p></p>
    <textarea readonly class="container-fluid">{{ board_objects.b_content }}</textarea>
    <div style="float:right">
        <button type="button"
                class="btn btn-success"
                id="list_btn">목록으로</button>
        <button type="button"
                class="btn btn-info"
                id="fix_btn"
                data-pageid={{ board_objects.id }}>수정하기</button>
        <button type="button"
                class="btn btn-danger"
                id="del_btn"
                data-b_del_url="{% url 'bbs:b_delete' board_objects.id %}">삭제하기</button>
        <button type="button"
                class="btn btn-warning"
                id="like_btn">좋아요</button>
    </div>
    <p></p>
    <h6>댓글</h6>
    <div class="container" style="background-color: antiquewhite">
        <table class="table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">작성자</th>
                    <th scope="col-10">댓글내용</th>
                    <th scope="col">삭제</th>
                </tr>
            </thead>
            <tbody id="TbodyPart">
                <tr style="background-color: lightsteelblue">
                    <td><input id="c_writer" class="col" placeholder="작성자"></td>
                    <td><input id="c_content" class="col-10" placeholder="댓글 내용"></td>
                    <td><button id="comment_btn" type="submit" class="btn btn-primary">등록</button></td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

bbs/templates/bbs/fix.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block html_body %}

<div class="container">

    <h1>글 수정하기</h1>

    <form {% comment %}action={% url 'bbs:b_list' %}{% comment %}action = "" : 현재 페이지로 request를 진행{% endcomment %}
          method="post">
        {% csrf_token %}
        <p></p>
        <div>
            글 번호 : {{ board_objects.id }}
        </div>
        <p></p>
        <div class="row">
            <div class="col-6">작성일 : {{ board_objects.b_date }}</div>
            <div class="col-6">좋아요 : {{ board_objects.b_like_count }}</div>
        </div>
        <p></p>
        {% bootstrap_form board_form %}
        <div style="float:right">
            <button type="submit"
                    class="btn btn-info">수정하기</button>
            <button type="reset"
                    class="btn btn-danger"
                    onclick="history.back()">취소</button>
        </div>
    </form>
</div>
{% endblock %}

bbs/templates/bbs/list.html
{% extends 'base.html' %} {% comment %}기본틀 사용하기 위해 base.html을 이용한다.{% endcomment %}
{% block html_body %} {% comment %}body 부분을 확장하기 위한 방법{% endcomment %}
<script src="/static/js/menu_btn.js"></script>  {% comment %}버튼에 대한 함수를 넣기 위한 자바스크립트{% endcomment %}
<div class="container">
  <h1>Bulletin Board System(BBS)</h1>
  <div class="row">
    <button type="button"
          class="btn btn-primary col-1"
          id="new_post_btn">새글 작성</button>
    <div class="col-7"></div>
    <input type="text" class="col-3">
    <button type="button" class="col-1">검색</button>
  </div>
  <table class="table table-hover">
    <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">글제목</th>
      <th scope="col">글작성자</th>
      <th scope="col">글작성일</th>
      <th scope="col">댓글수</th>
      <th scope="col">좋아요</th>
    </tr>
    </thead>
    <tbody>
    {% for post in posts %}
    <tr>
      <th scope="row">{{ post.id }}</th>
      <td><a href="/bbs/{{ post.id }}/detail/">{{ post.b_title }}</a></td>
      <td>{{ post.b_author }}</td>
      <td>{{ post.b_date }}</td>
      <td>{{ post.b_comment_count }}</td>
      <td>{{ post.b_like_count }}</td>
    </tr>
    {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="ko">
  <head>
    <meta charset="utf-8">
    <title>{{ page_title }}</title>

    <!-- JQuery CDN -->
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    {% block html_header %}
    {% endblock %}
  </head>
  <body>
    {% block html_body %}
    {% endblock %}
  </body>
</html>
{% comment %}템플릿 확장하기 : 모든 html에 어차피 쓸 Jquery, Bootstrap을 base로 추가해 줄 수 있도록 하는 헤드 코드는 위처럼 만들 수 있다.{% endcomment %}
{% comment %}여기서 확장 구간은 head 부분 블락구간과 body 부분 블락구간으로 두 가지가 가능하다.{% endcomment %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>메인페이지입니다!</h1>
    <br><br><br>
    <a href="bbs/list/">Enter BSS</a>    {% comment %}누르면 게시글 list 페이지로 들어가야 함.{% endcomment %}
    {% comment %}
        절대경로 : /bbs/list/ -> http://localhost:8000/bbs/list/
        상대경로 : bbs/list/ -> 현재 page(index.html을 읽는 경로)(http://localhost:8000/) + bbs/list/
    {% endcomment %}
</body>
</html>